variable environment { default = "N/A" }
variable env_stage { default = "N/A" }
variable aws_region_code { default = "N/A" }
variable service_level { default = "N/A" }
variable aspire_code { default = "N/A" }
variable application_name { default = "N/A" }
variable application_component { default = "N/A" }
variable sid { default = "N/A" }
variable instance_no { default = "N/A"}